let sessionId=null,pendingId=null;
const feed=document.getElementById("feed"),input=document.getElementById("input"),form=document.getElementById("composer"),thinking=document.getElementById("thinking"),thinkingText=document.getElementById("thinkingText"),approval=document.getElementById("approval");
function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function addBlock(kind,html){const el=document.createElement("div");el.className="block "+kind;el.innerHTML=html;feed.appendChild(el);feed.scrollTop=feed.scrollHeight}
function showThinking(s){thinkingText.textContent=s;thinking.classList.add("active")}function hideThinking(){thinking.classList.remove("active")}function setBusy(v){input.disabled=v;document.querySelector(".send").disabled=v}
async function init(){const c=await fetch("/api/config").then(r=>r.json());document.getElementById("model").textContent=c.model;document.getElementById("targets").textContent=c.servers.length+" target"+(c.servers.length===1?"":"s");document.getElementById("memory").textContent="memory "+c.memory_items;sessionId=(await fetch("/api/session",{method:"POST"}).then(r=>r.json())).session_id}
init().catch(e=>addBlock("assistant-block",'<div class="content fail">Connection error: '+esc(e.message)+"</div>"));
async function sendMessage(text){addBlock("user-block",'<div class="prompt-line"><span class="sigil">›</span><span>you</span></div><div class="content">'+esc(text)+"</div>");setBusy(true);showThinking("thinking / planning");try{const d=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({session_id:sessionId,message:text})}).then(r=>r.json());hideThinking();handle(d)}catch(e){hideThinking();addBlock("assistant-block",'<div class="content fail">'+esc(e.message)+"</div>")}finally{setBusy(false);input.focus()}}
function handle(d){if(d.type==="approval"){pendingId=d.pending_id;document.getElementById("approvalTool").textContent=d.tool;document.getElementById("approvalServer").textContent=d.server;document.getElementById("approvalRisk").textContent=d.classification.replace("_"," ");document.getElementById("approvalCommand").textContent=d.command;const p=document.getElementById("approvalPreview");if(d.preview){p.textContent=d.preview;p.classList.remove("hidden")}else{p.textContent="";p.classList.add("hidden")}document.getElementById("approvalTitle").textContent=d.tool==="write_file"?"Write proposed file":"Approve proposed change";approval.classList.remove("hidden");return}if(d.execution)addBlock("tool-block",'<div class="tool-head">COMMAND RESULT · '+esc(d.execution.server||"")+'</div><pre class="'+(d.execution.ok?"ok":"fail")+'">'+esc(d.execution.stdout||d.execution.stderr||d.execution.error||"no output")+"</pre>");if(d.type==="denied")addBlock("tool-block",'<div class="tool-head">ACTION DENIED</div><div class="muted">'+esc(d.content)+"</div>");else if(d.content)addBlock("assistant-block",'<div class="prompt-line"><span class="sigil">◆</span><span>serverhelpr</span></div><div class="content">'+esc(d.content)+"</div>")}
async function decide(decision,remember){if(!pendingId)return;const id=pendingId;pendingId=null;approval.classList.add("hidden");showThinking(decision==="allow"?"executing / verifying":"cancelling");setBusy(true);try{const d=await fetch("/api/approval/"+id,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({decision:decision,remember:!!remember})}).then(r=>r.json());hideThinking();handle(d)}catch(e){hideThinking();addBlock("assistant-block",'<div class="content fail">'+esc(e.message)+"</div>")}finally{setBusy(false);input.focus()}}
form.addEventListener("submit",e=>{e.preventDefault();const t=input.value.trim();if(!t||input.disabled)return;input.value="";input.style.height="auto";sendMessage(t)});input.addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();form.requestSubmit()}});input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,180)+"px"});document.querySelectorAll("[data-prompt]").forEach(b=>b.addEventListener("click",()=>sendMessage(b.dataset.prompt)));document.getElementById("deny").onclick=()=>decide("deny",false);document.getElementById("allow").onclick=()=>decide("allow",false);document.getElementById("allowRemember").onclick=()=>decide("allow",true);
